services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=database
      - PGPORT=5432
      - PGDATABASE=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app
    depends_on:
      - database

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/database/sql
      - ./database/sql:/docker-entrypoint-initdb.d
volumes:
  postgres-data:
